/**
 * Mock product data — replace with Sanity GROQ queries in Phase 3.
 *
 * All text fields are objects keyed by locale (en, ka, ru, tr, ar).
 * The `useLocalizedField` hook (see hooks/useLocalizedField.js) picks the right value.
 */

export const CATEGORIES = [
  { id: 'chair',     label: { en: 'Chair',     ka: 'სკამი',      ru: 'Стул',      tr: 'Sandalye',  ar: 'كرسي'    } },
  { id: 'table',     label: { en: 'Table',     ka: 'მაგიდა',    ru: 'Стол',      tr: 'Masa',      ar: 'طاولة'   } },
  { id: 'sofa',      label: { en: 'Sofa',      ka: 'სოფა',      ru: 'Диван',     tr: 'Koltuk',    ar: 'أريكة'   } },
  { id: 'bar-stool', label: { en: 'Bar Stool', ka: 'ბარის სკამი',ru: 'Барный стул',tr:'Bar Taburesi',ar:'كرسي بار'} },
  { id: 'counter',   label: { en: 'Counter',   ka: 'სტენდი',    ru: 'Стойка',    tr: 'Tezgah',    ar: 'كاونتر'  } },
  { id: 'shelving',  label: { en: 'Shelving',  ka: 'თაროები',   ru: 'Стеллажи',  tr: 'Raf',       ar: 'أرفف'    } },
  { id: 'fridge',    label: { en: 'Fridge',    ka: 'მაცივარი',  ru: 'Холодильник',tr:'Buzdolabı',  ar: 'ثلاجة'  } },
  { id: 'other',     label: { en: 'Other',     ka: 'სხვა',      ru: 'Другое',    tr: 'Diğer',     ar: 'أخرى'   } },
];

export const MOCK_PRODUCTS = [
  {
    _id: 'p1',
    slug: 'wooden-restaurant-chair',
    categoryId: 'chair',
    status: 'available',
    condition: 'good',
    quantity: 40,
    location: { en: 'Tbilisi, Saburtalo', ka: 'თბილისი, საბურთალო', ru: 'Тбилиси, Сабуртало', tr: 'Tiflis, Saburthalo', ar: 'تبليسي، سابورثالو' },
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80',
      'https://images.unsplash.com/photo-1549497538-303791108f95?w=800&q=80',
    ],
    title: {
      en: 'Wooden Restaurant Chair',
      ka: 'ხის რესტორნის სკამი',
      ru: 'Деревянный ресторанный стул',
      tr: 'Ahşap Restoran Sandalyesi',
      ar: 'كرسي مطعم خشبي',
    },
    description: {
      en: 'Solid wood restaurant chairs in excellent condition. Classic design that fits any restaurant or café setting. Durable construction, comfortable seating.',
      ka: 'მყარი ხის სკამები, შესანიშნავ მდგომარეობაში. კლასიკური დიზაინი, რომელიც შეეფერება ნებისმიერ რესტორანს.',
      ru: 'Крепкие деревянные стулья в отличном состоянии. Классический дизайн подходит для любого ресторана.',
      tr: 'Mükemmel durumda sağlam ahşap restoran sandalyeleri.',
      ar: 'كراسي مطعم من الخشب الصلب بحالة ممتازة.',
    },
  },
  {
    _id: 'p2',
    slug: 'round-cafe-table',
    categoryId: 'table',
    status: 'available',
    condition: 'good',
    quantity: 25,
    location: { en: 'Tbilisi, Vake', ka: 'თბილისი, ვაკე', ru: 'Тбилиси, Ваке', tr: 'Tiflis, Vake', ar: 'تبليسي، فاكي' },
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
      'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80',
    ],
    title: {
      en: 'Round Café Table 70cm',
      ka: 'მრგვალი კაფეს მაგიდა 70სმ',
      ru: 'Круглый стол для кафе 70см',
      tr: 'Yuvarlak Kafe Masası 70cm',
      ar: 'طاولة مقهى دائرية 70 سم',
    },
    description: {
      en: 'Round café tables with metal base. 70cm diameter, perfect for 2-person settings. Lightweight and stackable.',
      ka: 'მრგვალი კაფეს მაგიდები მეტალის ფეხით. 70სმ დიამეტრი.',
      ru: 'Круглые столы для кафе с металлическим основанием. Диаметр 70см.',
      tr: 'Metal ayaklı yuvarlak kafe masaları. 70cm çap.',
      ar: 'طاولات مقهى دائرية بقاعدة معدنية. قطر 70 سم.',
    },
  },
  {
    _id: 'p3',
    slug: 'bar-sofa-set',
    categoryId: 'sofa',
    status: 'limited',
    condition: 'ok',
    quantity: 6,
    location: { en: 'Tbilisi, Didube', ka: 'თბილისი, დიდუბე', ru: 'Тбилиси, Дидубе', tr: 'Tiflis, Didube', ar: 'تبليسي، ديدوبي' },
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    ],
    title: {
      en: 'Lounge Sofa Set',
      ka: 'ლაუნჯ სოფას ნაკრები',
      ru: 'Комплект диванов для лаунжа',
      tr: 'Lounge Koltuk Takımı',
      ar: 'طقم أرائك صالة الانتظار',
    },
    description: {
      en: 'Comfortable lounge sofas in good condition. Fabric upholstery, dark grey. Sold as a set of 2.',
      ka: 'კომფორტული ლაუნჯ სოფები. ქსოვილის გარეკანი, მუქი ნაცრისფერი.',
      ru: 'Комфортные диваны для лаунжа. Тканевая обивка, тёмно-серая.',
      tr: 'Konforlu lounge koltukları, iyi durumda. Kumaş döşeme, koyu gri.',
      ar: 'أرائك صالة مريحة بحالة جيدة. تنجيد قماشي، رمادي داكن.',
    },
  },
  {
    _id: 'p4',
    slug: 'metal-bar-stool',
    categoryId: 'bar-stool',
    status: 'available',
    condition: 'good',
    quantity: 60,
    location: { en: 'Tbilisi, Saburtalo', ka: 'თბილისი, საბურთალო', ru: 'Тбилиси, Сабуртало', tr: 'Tiflis, Saburthalo', ar: 'تبليسي، سابورثالو' },
    images: [
      'https://images.unsplash.com/photo-1503602642458-232111445657?w=800&q=80',
    ],
    title: {
      en: 'Industrial Metal Bar Stool',
      ka: 'ინდუსტრიული მეტალის ბარის სკამი',
      ru: 'Индустриальный металлический барный стул',
      tr: 'Endüstriyel Metal Bar Taburesi',
      ar: 'كرسي بار معدني صناعي',
    },
    description: {
      en: 'Industrial-style metal bar stools with footrest. Height 75cm. Powder-coated matte black finish. Stackable.',
      ka: 'ინდუსტრიული სტილის მეტალის სკამები ფეხის სადგამით. სიმაღლე 75სმ.',
      ru: 'Металлические барные стулья в индустриальном стиле с подставкой для ног. Высота 75см.',
      tr: 'Ayak dayamalı endüstriyel tarz metal bar tabureleri. Yükseklik 75cm.',
      ar: 'كراسي بار معدنية بطراز صناعي مع استناد للقدم. الارتفاع 75 سم.',
    },
  },
  {
    _id: 'p5',
    slug: 'commercial-fridge',
    categoryId: 'fridge',
    status: 'available',
    condition: 'ok',
    quantity: 3,
    location: { en: 'Tbilisi, Isani', ka: 'თბილისი, ისანი', ru: 'Тбилиси, Исани', tr: 'Tiflis, Isani', ar: 'تبليسي، إيساني' },
    images: [
      'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&q=80',
    ],
    title: {
      en: 'Commercial Display Fridge',
      ka: 'კომერციული სარეკლამო მაცივარი',
      ru: 'Коммерческий витринный холодильник',
      tr: 'Ticari Teşhir Buzdolabı',
      ar: 'ثلاجة عرض تجارية',
    },
    description: {
      en: 'Upright commercial display fridge. 400L capacity, glass door. Perfect for beverages and food display.',
      ka: 'ვერტიკალური კომერციული მაცივარი. 400ლ მოცულობა, მინის კარი.',
      ru: 'Вертикальный коммерческий холодильник. Объём 400л, стеклянная дверь.',
      tr: 'Dik ticari teşhir buzdolabı. 400L kapasite, cam kapı.',
      ar: 'ثلاجة عرض تجارية مستقيمة. سعة 400 لتر، باب زجاجي.',
    },
  },
  {
    _id: 'p6',
    slug: 'shelving-unit',
    categoryId: 'shelving',
    status: 'available',
    condition: 'good',
    quantity: 15,
    location: { en: 'Tbilisi, Gldani', ka: 'თბილისი, გლდანი', ru: 'Тбилиси, Глдани', tr: 'Tiflis, Gldani', ar: 'تبليسي، غلداني' },
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    title: {
      en: 'Heavy-Duty Steel Shelving',
      ka: 'მძიმე ფოლადის თარო',
      ru: 'Прочные металлические стеллажи',
      tr: 'Ağır Hizmet Çelik Raf',
      ar: 'رف فولاذي للاستخدام الثقيل',
    },
    description: {
      en: 'Heavy-duty steel shelving units. 5 shelves, 180cm height, 90cm width. Ideal for storage rooms and commercial kitchens.',
      ka: 'მძიმე ფოლადის სარდაფის თაროები. 5 თარო, 180სმ სიმაღლე.',
      ru: 'Прочные металлические стеллажи. 5 полок, высота 180см, ширина 90см.',
      tr: 'Ağır hizmet çelik raf üniteleri. 5 raf, 180cm yükseklik.',
      ar: 'وحدات رف فولاذية للاستخدام الثقيل. 5 رفوف، ارتفاع 180 سم.',
    },
  },
  {
    _id: 'p7',
    slug: 'outdoor-wicker-chair',
    categoryId: 'chair',
    status: 'available',
    condition: 'good',
    quantity: 30,
    location: { en: 'Tbilisi, Vake', ka: 'თბილისი, ვაკე', ru: 'Тбилиси, Ваке', tr: 'Tiflis, Vake', ar: 'تبليسي، فاكي' },
    images: [
      'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80',
    ],
    title: {
      en: 'Outdoor Rattan Chair',
      ka: 'გარე რატანის სკამი',
      ru: 'Уличный плетёный стул',
      tr: 'Dış Mekan Rattan Sandalye',
      ar: 'كرسي روطان خارجي',
    },
    description: {
      en: 'Weather-resistant outdoor rattan chairs. Suitable for terraces, gardens, and outdoor dining areas.',
      ka: 'ამინდგამძლე გარე რატანის სკამები. შეეფერება ტერასებს.',
      ru: 'Погодоустойчивые плетёные стулья для улицы. Подходят для террас.',
      tr: 'Hava koşullarına dayanıklı dış mekan rattan sandalyeleri.',
      ar: 'كراسي روطان خارجية مقاومة للطقس.',
    },
  },
  {
    _id: 'p8',
    slug: 'reception-counter',
    categoryId: 'counter',
    status: 'limited',
    condition: 'good',
    quantity: 2,
    location: { en: 'Tbilisi, Saburtalo', ka: 'თბილისი, საბურთალო', ru: 'Тбилиси, Сабуртало', tr: 'Tiflis, Saburthalo', ar: 'تبليسي، سابورثالو' },
    images: [
      'https://images.unsplash.com/photo-1534536281715-e28d76689b4d?w=800&q=80',
    ],
    title: {
      en: 'Bar / Reception Counter',
      ka: 'ბარის / მიმღების სტენდი',
      ru: 'Барная / ресепшн стойка',
      tr: 'Bar / Resepsiyon Tezgahı',
      ar: 'كاونتر بار / استقبال',
    },
    description: {
      en: 'Modern bar counter with built-in sink compartment. 200cm length, dark wood finish with steel accents.',
      ka: 'თანამედროვე ბარის სტენდი ჩაშენებული ნიჟარით. 200სმ სიგრძე.',
      ru: 'Современная барная стойка со встроенной раковиной. Длина 200см.',
      tr: 'Yerleşik lavabolu modern bar tezgahı. 200cm uzunluk.',
      ar: 'كاونتر بار حديث مع حوض مدمج. طول 200 سم.',
    },
  },
];
