export const siteStrings = {
  name: 'siteStrings',
  title: 'Site Strings (Translations)',
  type: 'document',
  icon: () => '💬',
  groups: [
    { name: 'config',   title: 'Configuration', default: true },
    { name: 'nav',      title: 'Navigation' },
    { name: 'topbar',   title: 'Top Bar' },
    { name: 'filters',  title: 'Filters' },
    { name: 'product',  title: 'Product Page' },
    { name: 'home',     title: 'Home Page' },
    { name: 'footer',   title: 'Footer' },
    { name: 'meta',     title: 'SEO & Metadata' },
  ],
  fields: [
    {
      name: 'useDynamicStrings',
      title: 'Translation Mode',
      type: 'boolean',
      group: 'config',
      initialValue: false,
      description: 'Enable to manage website translations dynamically through Sanity. Disable to fallback to static JSON files.',
    },
    // ── Navigation ──────────────────────────────────────────
    {
      name: 'nav__search',
      title: 'Search Placeholder',
      type: 'localizedString',
      group: 'nav',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'nav__contact',
      title: 'Contact Text',
      type: 'localizedString',
      group: 'nav',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'nav__call',
      title: 'Call Text',
      type: 'localizedString',
      group: 'nav',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'nav__chat',
      title: 'Chat Text',
      type: 'localizedString',
      group: 'nav',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    // ── Top Bar ─────────────────────────────────────────────
    {
      name: 'topbar__contact',
      title: 'Top Bar Contact Label',
      type: 'localizedString',
      group: 'topbar',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    // ── Filters ─────────────────────────────────────────────
    {
      name: 'filters__all',
      title: 'All Filter Label',
      type: 'localizedString',
      group: 'filters',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'filters__available',
      title: 'Available Filter Label',
      type: 'localizedString',
      group: 'filters',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'filters__limited',
      title: 'Limited Filter Label',
      type: 'localizedString',
      group: 'filters',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    // ── Product Page ────────────────────────────────────────
    {
      name: 'product__condition',
      title: 'Condition Label',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__quantity',
      title: 'Quantity Label',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__location',
      title: 'Location Label',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__category',
      title: 'Category Label',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__description',
      title: 'Description Label',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__call',
      title: 'Call Button',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__chat',
      title: 'Chat Button',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__back',
      title: 'Back to Catalog Link',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__similar',
      title: 'Similar Items Title',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__condition_good',
      title: 'Condition: Good',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__condition_ok',
      title: 'Condition: Fair',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__condition_used',
      title: 'Condition: Used',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__status_available',
      title: 'Status: Available',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__status_limited',
      title: 'Status: Limited',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__status_sold',
      title: 'Status: Sold',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'product__contact_cta',
      title: 'Unified Contact Button',
      type: 'localizedString',
      group: 'product',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    // ── Home Page ───────────────────────────────────────────
    {
      name: 'home__title',
      title: 'Hero Title',
      type: 'localizedString',
      group: 'home',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'home__subtitle',
      title: 'Hero Subtitle',
      type: 'localizedText',
      group: 'home',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'home__items_found',
      title: 'Items Found Count Label (Use {{count}} placeholder)',
      type: 'localizedString',
      group: 'home',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'home__no_results',
      title: 'No Results Title',
      type: 'localizedString',
      group: 'home',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'home__no_results_hint',
      title: 'No Results Hint',
      type: 'localizedString',
      group: 'home',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'home__clear_filters',
      title: 'Clear Filters Button',
      type: 'localizedString',
      group: 'home',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'home__load_more',
      title: 'Load More Button',
      type: 'localizedString',
      group: 'home',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    // ── Footer ──────────────────────────────────────────────
    {
      name: 'footer__tagline',
      title: 'Footer Tagline',
      type: 'localizedText',
      group: 'footer',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'footer__quick_links',
      title: 'Quick Links Header',
      type: 'localizedString',
      group: 'footer',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'footer__contact',
      title: 'Footer Contact Header',
      type: 'localizedString',
      group: 'footer',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'footer__all_rights',
      title: 'All Rights Reserved Label',
      type: 'localizedString',
      group: 'footer',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'footer__location',
      title: 'Footer Location Address',
      type: 'localizedString',
      group: 'footer',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    // ── SEO & Metadata ──────────────────────────────────────
    {
      name: 'meta__site_name',
      title: 'Site Name',
      type: 'localizedString',
      group: 'meta',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'meta__home_title',
      title: 'Home Page Meta Title',
      type: 'localizedString',
      group: 'meta',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
    {
      name: 'meta__home_desc',
      title: 'Home Page Meta Description',
      type: 'localizedText',
      group: 'meta',
      hidden: ({ document }) => !document?.useDynamicStrings,
    },
  ]
};
